# Kernel compile workflow for personal usage
# By Sarthak Roy (sarthakroy2002@gmail.com)

name: Kernel CI

on:
  workflow_dispatch:
    inputs:
      device:
          description: 'device codename (RMX2020/cancunf/air)'
          required: true
      repo:
          description: 'Kernel source link'
          required: true
      branch:
          description: 'Kernel source branch'
          required: true
      gki:
          description: 'Need GKI build? (true/false)'
          required: false 

env:
  TZ: Asia/Kolkata
  DEVICE: ${{ github.event.inputs.device }}
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  GKI: ${{ github.event.inputs.gki }}
  token: ${{ secrets.TOKEN }}
  chat_id: ${{ secrets.CHAT_ID }}

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initializing environment
        run: |
          git config --global user.name "Koushikdey2003"
          git config --global user.email "kousickdey3@gmail.com"
          df -h
          ld --version
          gcc -v
          ar --version
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex glibc-source g++-multilib gcc-multilib binutils-aarch64-linux-gnu git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2 tmate ssh neofetch
          neofetch

      - name: Lets compile
        run: |
          git clone $REPO -b $BRANCH kernel 
          cd kernel
          if [ "${DEVICE}" = "RMX2020" ]; then
            wget https://raw.githubusercontent.com/sarthakroy2002/Scripts/main/Kernel/C3_build_script.sh
            bash C3_build_script.sh
          elif [ "${DEVICE}" = "cancunf" ] || [ "${GKI}" = "true" ]; then
            wget https://raw.githubusercontent.com/sarthakroy2002/Scripts/main/Kernel/cancunf_gki_build_script.sh
            bash cancunf_gki_build_script.sh
          else
            wget https://raw.githubusercontent.com/sarthakroy2002/Scripts/main/Kernel/cancunf_build_script.sh
            bash cancunf_build_script.sh
          fi

          if [ "${DEVICE}" = "air" ] || [ "${GKI}" = "true" ]; then
            wget https://raw.githubusercontent.com/Koushikdey2003/Scripts/main/Kernel/air_gki_build_script.sh
            bash air_gki_build_script.sh
          else
            wget https://raw.githubusercontent.com/Koushikdey2003/Scripts/main/Kernel/air_build_script.sh
            bash air_build_script.sh
          fi
