# Kernel compile workflow
name: Kernel CI

on:
  push:
    branches:
      - air-5.15

  workflow_dispatch:

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Initializing environment
        run: |
          git config --global user.name "Koushikdey2003"
          git config --global user.email "kousickdey3@gmail.com"
          df -h
          ld --version
          gcc -v
          ar --version
          sudo apt update -y
          sudo apt install -y bc bison build-essential ccache curl flex glibc-source g++-multilib gcc-multilib binutils-aarch64-linux-gnu git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python-is-python3 tmate ssh neofetch
          sudo apt-get install repo -y
          repo --version
          neofetch
          df -h
          ccache -M 100G
          export USE_CCACHE=1
          ccache --show-stats

      - name: Lets compile
        env:
          TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          mkdir kernel
          cd kernel
          repo init -u https://github.com/Koushikdey2003/kernel_manifest-air-5.15.git -b common-android13-5.15 --depth=1
          repo sync --force-sync
          echo "Compile starting..."
          BUILD_CONFIG=kernel-5.15/build.config.mtk.aarch64.mgk build/build.sh
          echo "Compilied..."
          ccache --show-stats
          ccache --show-config
          ls out/android13-5.15/dist > list.txt
          git clone https://github.com/Koushikdey2003/AnyKernel3 -b air --depth=1
          cp -r out/android13-5.15/dist/Image.gz AnyKernel3
          cd AnyKernel3
          zip -r9 android13-5.15-AnyKernel3.zip ./*

      - uses: actions/upload-artifact@v4
        with:
          name: android13-5.15 Flashable Zip and Kernel Binary
          path: |
            kernel/AnyKernel3/android13-5.15-AnyKernel3.zip
            kernel/out/android13-5.15/dist/Image.gz
            kernel/out/android13-5.15/dist/mt6835.dtb
            kernel/list.txt
